# Generated by Django 6.0.4 on 2026-04-12 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peak_wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parque',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='peak_wishlist.pais'),
        ),
    ]
