# Generated by Django 6.0.4 on 2026-04-12 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peak_wishlist', '0002_parque_pais'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refugio',
            old_name='mountain',
            new_name='montana',
        ),
    ]
