# Generated by Django 6.0.4 on 2026-04-12 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peak_wishlist', '0003_rename_mountain_refugio_montana'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actividad',
            old_name='equipo_tulizado',
            new_name='equipo_utilizado',
        ),
    ]
