# Generated by Django 6.0.4 on 2026-04-13 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peak_wishlist', '0004_rename_equipo_tulizado_actividad_equipo_utilizado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={'verbose_name': 'Actividad', 'verbose_name_plural': 'Actividades'},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'verbose_name': 'Pais', 'verbose_name_plural': 'Paises'},
        ),
        migrations.AlterModelOptions(
            name='parque',
            options={'verbose_name': 'Parque', 'verbose_name_plural': 'Parques'},
        ),
        migrations.RemoveField(
            model_name='montana',
            name='pais',
        ),
        migrations.AlterField(
            model_name='pais',
            name='continente',
            field=models.CharField(choices=[('America', 'America'), ('Europa', 'Europa'), ('Africa', 'Africa'), ('Oceania', 'Oceania'), ('Asia', 'Asia')], max_length=20),
        ),
        migrations.AlterField(
            model_name='refugio',
            name='montana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peak_wishlist.montana', verbose_name='montaña'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='montana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peak_wishlist.montana', verbose_name='montaña'),
        ),
        migrations.AddField(
            model_name='montana',
            name='pais',
            field=models.ManyToManyField(to='peak_wishlist.pais'),
        ),
    ]
