# Generated by Django 6.0.4 on 2026-04-14 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peak_wishlist', '0005_alter_actividad_options_alter_pais_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Actividad',
            new_name='Excursion',
        ),
        migrations.AlterModelOptions(
            name='excursion',
            options={'verbose_name': 'Excursion', 'verbose_name_plural': 'Excursiones'},
        ),
    ]
