# Generated by Django 6.0.4 on 2026-04-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peak_wishlist', '0006_rename_actividad_excursion_alter_excursion_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ruta',
            old_name='restricciones',
            new_name='indicaciones_inicio_ruta',
        ),
        migrations.AddField(
            model_name='ruta',
            name='observaciones',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='montana',
            name='pais',
            field=models.ManyToManyField(related_name='montanas', to='peak_wishlist.pais'),
        ),
    ]
