# Generated by Django 6.0.4 on 2026-04-15 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peak_wishlist', '0007_rename_restricciones_ruta_indicaciones_inicio_ruta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(blank=True, choices=[('Planificado', 'Planificado'), ('Cumbre/Completado', 'Completado')], max_length=20),
        ),
    ]
