# Generated by Django 6.0.4 on 2026-04-15 03:06

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peak_wishlist', '0008_proyecto_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='presupuesto_general',
            field=djmoney.models.fields.MoneyField(decimal_places=0, max_digits=8),
        ),
    ]
