# Generated by Django 6.0.4 on 2026-04-16 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peak_wishlist', '0009_alter_proyecto_presupuesto_general'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='exigencia',
            field=models.CharField(choices=[('Treking/escalada de un Dia', 'Un Dia'), ('Trekking/escalada de Fin de Semana', 'Dos Dias'), ('Varios Dias en Montaña', 'Varios Dias'), ('Gran Recorrido', 'Gran Recorrido'), ('Recorrido Local', 'Recorrido Local')], max_length=50),
        ),
    ]
