# Generated by Django 6.0.4 on 2026-04-27 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peak_wishlist', '0010_alter_ruta_exigencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='montana',
            name='provincia_estado_departamento_region',
        ),
        migrations.AddField(
            model_name='montana',
            name='informacion_general',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='parque',
            name='informacion_general',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='ruta',
            name='informacion_general',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
