# Generated by Django 6.0.4 on 2026-04-28 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peak_wishlist', '0011_remove_montana_provincia_estado_departamento_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='actividad',
            field=models.CharField(choices=[('Alta Montaña', 'Alta Montana'), ('Escalada', 'Escalada En Roca'), ('Trekking', 'Trekking'), ('Bicicleta de Montaña', 'Mtb')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='dificultad_tecnica',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='exigencia',
            field=models.CharField(choices=[('Treking/escalada de un Dia', 'Un Dia E'), ('Trekking/escalada de Fin de Semana', 'Dos Dias'), ('Varios Dias en Montaña', 'Varios Dias'), ('Gran Recorrido', 'Gran Recorrido'), ('Recorrido Local', 'Recorrido Local')], max_length=50),
        ),
    ]
